// Generated by CoffeeScript 1.7.1
(function() {
  var n;

  $('#boo').hide("image");

  $('#bewareButton').click(function() {
    return $('#boo').toggle("image")([duration(400)]);
  });

  n = 1;

  $('#trick').click(function() {
    n = n + 1;
    return $('#counter').html(n);
  });

  $('#reset').click(function() {
    return $('#counter').html(1);
  });

}).call(this);

//# sourceMappingURL=main.map
