// Generated by CoffeeScript 1.7.1
(function() {
  var n;

  $('#bewareButton').click(function() {
    return $('#boo').append("Boo!");
  });

  n = 1;

  $('#trick').click(function() {
    n = n + 1;
    return $('#counter').html(n);
  });

}).call(this);

//# sourceMappingURL=main.map
